version: "3"

services: 
  cineflix:
    build: .
    container_name: cineflix
    restart: always
    entrypoint: 'sh -c ./init.sh'
    ports: 
      - "5555:5555"
    volumes: 
      - ./:/usr/src/cineflix
    networks:
      - cineflix_connect
    environment: 
      DATABASE_URL: ${DATABASE_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_DATABASE: ${DB_DATABASE}
      DB_PASSWORD: ${DB_PASSWORD}

  cineflix_database_adm:
    image: adminer
    container_name: cineflix_database_adm
    ports:
      - 8080:8080
    networks:
      - cineflix_connect

  cineflix_database:
    image: postgres
    restart: always
    container_name: cineflix_database
    environment: 
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports: 
      - "5432:5432"
    networks:
      - cineflix_connect
      
networks: 
  cineflix_connect:
    driver: bridge






