version: "3"

services: 
  app:
    build: .
    container_name: app
    restart: always
    entrypoint: 'sh -c ./init.sh'
    ports: 
      - "5555:5555"
    volumes: 
      - ./:/usr/src/app
    networks:
      - app-connect
    environment: 
      DATABASE_URL: ${DATABASE_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_DATABASE: ${DB_DATABASE}
      DB_PASSWORD: ${DB_PASSWORD}

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
    networks:
      - app-connect

  pgsql:
    image: postgres
    restart: always
    container_name: pgsql
    environment: 
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports: 
      - "5432:5432"
    networks:
      - app-connect
      
networks: 
  app-connect:
    driver: bridge






